<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQAyy8rt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQAyy8rt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQAyy8rt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQAyy8rt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQAyy8rt\App_KernelDevDebugContainer([
    'container.build_hash' => 'QAyy8rt',
    'container.build_id' => 'c2d94207',
    'container.build_time' => 1652642385,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQAyy8rt');
